In [17]:
import array as arr
a=arr.array('i',[1,2,3])
for i in range (0,len(a)):
    print (a[i],end=" ")

1 2 3 

In [16]:
#1.

import array as arr

a=arr.array('i', [1, 3, 5, 3, 7, 9, 3])
print("The array is:",end=" ")
for i in range (0,len(a)):
    print (a[i],end=" ")
count=a.count(3);
print("\nNumber of occurrences of the number 3 in the said array: ",count)


The array is: 1 3 5 3 7 9 3 
Number of occurrences of the number 3 in the said array:  3


In [20]:
#2.
import array as arr
a=arr.array('i',[1,3,5,7,9])
print("The Original array is:",end=" ")
for i in range (0,len(a)):
    print (a[i],end=" ")
    a.append(a[i])

print("\nThe Extended array is:",end=" ")
for i in range (0,len(a)):
    print (a[i],end=" ")

The Original array is: 1 3 5 7 9 
The Extended array is: 1 3 5 7 9 1 3 5 7 9 

In [32]:
#3.
import numpy as np
l=[12.23,13.32,100.00,36.32]
arr=np.array((l))
print(arr)



[ 12.23  13.32 100.    36.32]


In [33]:
#4.
import numpy as np
arr=np.array([1,2,3,4,5],dtype=np.float64)
print("Size of the array:",arr.size)

print("Length of one array element in bytes:",arr.itemsize)
print("Total bytes consumed by the elements of the array:", arr.nbytes)

Size of the array: 5
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 40


In [34]:
#5.
import numpy as np
a=np.array(([[3,7],[2,4]]))
a=a*5
print(a)

[[15 35]
 [10 20]]


In [36]:
#6.
import numpy as np
u = np.array(([3, -2]))
v = np.array(([5, 1]))
print(np.dot(u,v))


13


In [46]:
#7.
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

result = np.cross(A, B)

print("Result of matrix multiplication A×B:")
print(result)


Result of matrix multiplication A×B:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [49]:
#8.
import numpy as np

M = np.array([[4, 2, 1],
              [1, 3, 0],
              [2, 1, 5]])

x = np.array([2, -1, 3])

result = np.dot(M, x)

print("Result of the matrix-vector product Mx:")
print(result)


Result of the matrix-vector product Mx:
[ 9 -1 18]


In [50]:
#9.
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

result = np.dot(A, B)

print("Result of matrix multiplication A×B:")
print(result)


Result of matrix multiplication A×B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [51]:
# 10.
import numpy as np

M = np.array([[[4, 2, 1],
               [1, 3, 0],
               [2, 1, 5]],
              
              [[-1, 2, 3],
               [0, -3, 1],
               [2, 1, 0]]])

x = np.array([2, -1, 3])

result = np.matmul(M, x)

# Alternatively, you can use the @ operator
# result = M @ x

print("Result of the matrix-vector product Mx:")
print(result)


Result of the matrix-vector product Mx:
[[ 9 -1 18]
 [ 5  6  3]]


In [52]:
#11.
import numpy as np

def is_prime(num):
    """Check if a number is prime."""
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find the first 20 prime numbers
primes = [i for i in range(2, 100) if is_prime(i)][:20]

# Create a NumPy array
prime_array = np.array(primes)

# Find the sum of the elements in the array
sum_of_primes = np.sum(prime_array)

print("First 20 prime numbers:")
print(prime_array)
print("\nSum of the elements:", sum_of_primes)


First 20 prime numbers:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]

Sum of the elements: 639


In [53]:
#12.
import numpy as np

temperatures = np.array([25.5, 26.2, 24.8, 23.5, 27.0, 25.9, 28.3])

# Calculate the mean temperature
mean_temperature = np.mean(temperatures)

# Identify indices where the temperature is above the mean
above_mean_indices = np.where(temperatures > mean_temperature)

print("Mean Temperature:", mean_temperature)
print("Indices where temperature is above the mean:", above_mean_indices)


Mean Temperature: 25.88571428571429
Indices where temperature is above the mean: (array([1, 4, 5, 6], dtype=int64),)


In [54]:
#13.
import numpy as np

# Create a NumPy array with elements ranging from 10 to 50
my_array = np.arange(10, 51)

# Extract elements from index 5 to index 15 (inclusive)
subset_array = my_array[5:16]

print("Original Array:")
print(my_array)

print("\nSubset Array (elements from index 5 to index 15):")
print(subset_array)



Original Array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Subset Array (elements from index 5 to index 15):
[15 16 17 18 19 20 21 22 23 24 25]


In [56]:
# 14.
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Extract the central 2x2 submatrix
submatrix = matrix[1:3, 1:3]

print("Original Matrix:")
print(matrix)

print("\nCentral 2x2 Submatrix:")
print(submatrix)


Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Central 2x2 Submatrix:
[[ 6  7]
 [10 11]]
2


In [57]:
#15.
import numpy as np

# Create a random 5x5 NumPy array with values between 0 and 1
random_array = np.random.rand(5, 5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(random_array)

print("Random 5x5 Array:")
print(random_array)

print("\nDiagonal Elements (as a 1D array):")
print(diagonal_elements)


Random 5x5 Array:
[[0.58973354 0.63061029 0.1475171  0.72601094 0.23869556]
 [0.18853783 0.83135045 0.7251685  0.16717209 0.75310147]
 [0.21593756 0.79402283 0.52945232 0.66554246 0.86835797]
 [0.14296902 0.42750849 0.64786876 0.88415752 0.70692476]
 [0.0112689  0.04698156 0.3819446  0.45015892 0.70847493]]

Diagonal Elements (as a 1D array):
[0.58973354 0.83135045 0.52945232 0.88415752 0.70847493]


In [58]:
#16.
import numpy as np

# Create a random 3D NumPy array with shape (3, 4, 5)
tensor = np.random.rand(3, 4, 5)

# Extract the subarray
subarray = tensor[1:3, 0, :]

print("Original 3D Array:")
print(tensor)

print("\nSubarray (from the first row of the second matrix to the third row of the third matrix):")
print(subarray)


Original 3D Array:
[[[0.38064611 0.2818779  0.39843724 0.36657003 0.25761824]
  [0.8278676  0.51685776 0.10829682 0.07428775 0.70565517]
  [0.12001918 0.69295028 0.87279958 0.71444879 0.75952872]
  [0.34090571 0.37565812 0.44385474 0.65397661 0.13519156]]

 [[0.27820697 0.87053456 0.73564997 0.72853853 0.43894776]
  [0.08358509 0.3213914  0.94544085 0.42085375 0.31591104]
  [0.62073893 0.39176137 0.21324716 0.6357432  0.94023164]
  [0.56052544 0.02743672 0.60240447 0.93636417 0.98965807]]

 [[0.47727119 0.4561053  0.43513044 0.83119037 0.05429848]
  [0.58325436 0.17101733 0.18287052 0.65441866 0.15760629]
  [0.38537579 0.15092611 0.66080445 0.87129644 0.85835541]
  [0.1515228  0.73112896 0.07588797 0.02614827 0.47640908]]]

Subarray (from the first row of the second matrix to the third row of the third matrix):
[[0.27820697 0.87053456 0.73564997 0.72853853 0.43894776]
 [0.47727119 0.4561053  0.43513044 0.83119037 0.05429848]]


In [59]:
#17.
import numpy as np

data = np.array([10, 25, 15, 30, 20, 35, 5])

# Calculate the mean of the original array
mean_value = np.mean(data)

# Create a new array containing elements greater than the mean
new_array = data[data > mean_value]

print("Original Array:")
print(data)

print("\nMean of the Original Array:", mean_value)

print("\nNew Array (elements greater than the mean):")
print(new_array)


Original Array:
[10 25 15 30 20 35  5]

Mean of the Original Array: 20.0

New Array (elements greater than the mean):
[25 30 35]


In [68]:
#18.
import numpy as np

# Generate a random 2D NumPy array with shape (5, 3) and values between 1 and 100
random_array = np.random.randint(1, 101, size=(5, 3))

# Extract rows where the sum of elements in the second column is greater than 150
selected_rows = random_array[random_array[:, 1].sum(axis=0) > 150]

print("Random 2D Array:")
print(random_array)

print("\nSelected Rows (where the sum of elements in the second column is greater than 150):")
print(selected_rows)


Random 2D Array:
[[90 42 53]
 [21 41 94]
 [65 47 13]
 [ 2 96  1]
 [89 94 32]]

Selected Rows (where the sum of elements in the second column is greater than 150):
[[[90 42 53]
  [21 41 94]
  [65 47 13]
  [ 2 96  1]
  [89 94 32]]]
